language: objective-c
before_install:
  brew install python3
matrix:
  include:
    - os: osx
      osx_image: xcode8
      env: TARGET=framework COMMAND=test FBSIMULATORCONTROL_DEVICE_SET=custom FBSIMULATORCONTROL_LAUNCH_TYPE=simulator_app
    - os: osx
      osx_image: xcode8
      env: TARGET=framework COMMAND=test FBSIMULATORCONTROL_DEVICE_SET=custom FBSIMULATORCONTROL_LAUNCH_TYPE=direct
script: ./build.sh
branches:
  only:
    - pxctest
